[window]
opacity = 0.8
startup_mode = "Fullscreen"

[font.normal]
family = "AdwaitaMonoNerdFont"
style = "Regular"

[font.bold]
family = "AdwaitaMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "AdwaitaMonoNerdFont"
style = "Bold Italic"

[font.italic]
family = "AdwaitaMonoNerdFont"
style = "Italic"
